# -*- coding: utf-8 -*-
"""aula030424.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pqral68fkUo7bd6OUZhCu4aAS0lmGu9c
"""

from matplotlib import pyplot as plt
x =[1,2,3,4,5,6]
y=[5,9,7,3,8,2]
plt.bar(x,y)

from matplotlib import pyplot as plt
x =[1,2,3,4,5,6]
y=[5,9,7,3,8,2]
plt.bar(x,y)

plt.title("grafico em barras")
plt.xlabel("eixo x")
plt.ylabel("eixo y")

plt.show()

from matplotlib import pyplot as plt
x1 =[1,2,3,4,5,6]
y1=[5,9,7,3,8,2]

x2 =[5,3,3,4,5,6]
y2=[8,0,7,3,7,2]
plt.bar(x1,y1,color ='g', label ="Barra 1" )
plt.bar(x2,y2,color ='r', label ="Barra 2")

plt.title("grafico em barras")
plt.xlabel("eixo x")
plt.ylabel("eixo y")
plt.legend()
plt.show()

from matplotlib import pyplot as plt
x1 =[1,2,3,4,5,6]
y1=[5,9,7,3,8,2]

x2 =[5,3,3,4,5,6]
y2=[8,0,7,3,7,2]

plt.plot(x1,y1,color ='g', label ="linha" )
plt.bar(x2,y2,color ='r', label ="Barra 1")

plt.title("grafico em barras")
plt.xlabel("eixo x")
plt.ylabel("eixo y")
plt.legend()
plt.show()

from matplotlib import pyplot as plt
x1 =[1,2,3,4,4,5]
y1=['rj','sp','rs','ac','vas','flu']

x2 =[5,5,6,6,6,7]
y2=['ba','bo','bi','ba','bu','bao']

x3 =[7,8,8,9,9,9]
y3=['du','da','dw','riio','lku','iku']

plt.barh(x1,y1,color ='g', label ="linha" )
plt.barh(x2,y2,color ='r', label ="Barra 1")
plt.barh(x3,y3,color ='b', label ="Barra 1")

plt.title("grafico em barras")
plt.xlabel("eixo x")
plt.ylabel("eixo y")
plt.legend()
plt.show()

from matplotlib import pyplot as plt
x1 =[3, 8, 1, 6, 4, 2]
y1=[5,9,7,3,8,2]

plt.scatter(x,y, s = 100)
plt.title("grafico com pontos")
plt.xlabel("eixo x")
plt.ylabel("eixo y")
plt.legend()
plt.show()

from matplotlib import pyplot as plt
x1 =[3, 8, 1, 6, 4, 2]
y1=['rj','sp','rs','ac','vas','flu']

x2 =[5, 0, 9, 2, 7, 4]
y2=['ba','bo','bi','ba','bu','bao']

x3 =[2, 6, 4, 1, 8, 3]
y3=['du','da','dw','riio','lku','iku']

plt.barh(x1,y1,color ='g', label ="linha" )
plt.barh(x2,y2,color ='r', label ="Barra 1")
plt.barh(x3,y3,color ='b', label ="Barra 1")

plt.title("grafico em barras")
plt.xlabel("eixo x")
plt.ylabel("eixo y")
plt.legend()
plt.show()

from matplotlib import pyplot as plt
x1 =[3, 8, 1, 6, 4, 2]
y1=[5,9,7,3,8,2]

plt.scatter(x,y, marker = 'P', color = 'r', label = "pontos", s = 100)
plt.plot (x,y , linestyle = "dashdot", color = 'g', label = "Linha")

plt.legend()

import matplotlib.pyplot as plt
x1 =[1, 2, 3, 4]
y1=[1,4,2,3]

plt.plot(x1,y1)
plt.grid(axis = 'x')
plt.show()

import matplotlib.pyplot as plt
x1 =[1, 2, 3, 4]
y1=[1,4,2,3]

plt.plot(x1,y1)
plt.grid(axis = 'y')
plt.show()

"""grafixco pizza

"""

import matplotlib.pyplot as plt
x1 =[1, 3, 6,7,8]
plt.pie(x)
plt.show()

import matplotlib.pyplot as plt
x =[1, 3, 6]
rotulos = ['DNA','RNA','FLAMENGO']

plt.title("GRÁFICO COM PORCENTAGEM")
plt.axis('equal')
plt.pie(x,labels=rotulos,autopct='%1.1f%%')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(10,10))
x =[1, 2, 3,4]
y =[1, 4, 2,3]
w = [9,2,9,2]
j = [2,9,4,7]
t =np.arange(0.01,5.0,0.01)
s =np.sin(2* np.pi *t)

plt.subplot(3,1,1)
plt.title("primeiro Gráfico")
plt.plot(x,y,label ="grafico 1 ",linestyle="dashdot",color='g')
plt.legend()
plt.subplot(2,3,6)


plt.subplot(3,1,2)
plt.title("terceiro Gráfico")
plt.plot(s,t,label ="grafico 2 ",linestyle="dashdot",color='b')
plt.legend()


plt.subplot(3,1,3)
plt.title("Segundo Gráfico")
plt.plot(w,j,label ="grafico 3 ",linestyle="dashdot",color='r')
plt.legend()

"""Graficos animados

"""

